version: '3'
services:

  nginx_reverse_proxy:
    # image: nginx:alpine
    build: .
    container_name: nginx_reverse_proxy
    restart: unless-stopped
    tty: true
    networks:
      - reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sites_available/:/etc/nginx/conf.d/
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - /home/ubuntu/ssl:/ssl/

networks:
    reverse_proxy:
       external: true
