version: "3"

services:
  # Database
  mysql_nimeshab:
    container_name: mysql_nimeshab
    image: mysql:5.7
    volumes:
      - ./files:/var/lib/mysql
    restart: always
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: 123
    networks:
      - nimeshab

  # phpmyadmin
  phpmyadmin_nimeshab:
    container_name: phpmyadmin_nimeshab
    image: phpmyadmin
    restart: always
#    ports:
#      - "8090:80"
    environment:
      PMA_HOST: mysql_nimeshab
      MYSQL_ROOT_PASSWORD: 123
    networks:
       - nimeshab

networks:
    nimeshab:
      external: true

